FROM mysql:8.0

#Sei que o correto seria não versionar informações sensíveis como a senha do banco, mas nesse caso como se trata de um container vazio, tanto faz..

ENV MYSQL_DATABASE=wtu_ancora
ENV MYSQL_USER=brabo
ENV MYSQL_PASSWORD=senhaSecreta
ENV MYSQL_ROOT_PASSWORD=admin

COPY ./script.sql /docker-entrypoint-initdb.d/

EXPOSE 3306