# Etapa de build
FROM maven:3.9.7-ibm-semeru-21-jammy AS build

WORKDIR /usr/app


COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY src ./src

RUN mvn clean package -DskipTests

FROM openjdk:21-jdk-slim

WORKDIR /app

VOLUME /tmp


COPY --from=build /usr/app/target/*.jar runner.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/runner.jar"]
